name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull from upstream
      run: |
        git remote add upstream https://github.com/pengzhile/pandora-cloud-serverless.git
        git fetch upstream
        git config pull.ff only  # 设置fast-forward only为默认选项
        git pull upstream master
        git push
