name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull from upstream
      run: |
        git remote add upstream https://github.com/pengzhile/pandora-cloud-serverless.git
        git fetch upstream
        git pull upstream master
        git checkout master # 切换到你的分支
        git merge upstream/master # 合并上游分支的改变
        git push
